const DEFAULT_IGNORES = [
  'node_modules',
  'dist',
  'dist.staging.*',
  'dist.__finalize_backup__.*',
  'dist.__sync_tmp__.*',
  'dist.__sync_backup__.*',
  'package-dist.__sync_tmp__.*',
  'package-dist.__sync_backup__.*',
  '.*.__sync_tmp__.*',
  '.*.__sync_backup__.*',
  '.tmp.*',
  '.backup.*',
  'packages/plugin-sdk/.example-builds',
  '.project',
  '.happier',
  '.happier-stack',
  'coverage',
  '/output',
  '.reviews',
  '.agent-contexts',
  '.dev',
  '.clawpatch',
  '.playwright-mcp',
  '.antigravitycli',
  'evidence',
  'graphify-out',
  '/workspace',
  '.expo',
  'target',
  '!packages/protocol/src/browser/target',
  '!packages/protocol/src/browser/target/**',
  'Pods',
  '.next',
  '.runner-snapshots',
  'package-dist',
  '.restore.*',
  '.dist.hstack-*',
  '.cxx',
  'apps/ui/ios/build',
  'apps/ui/android/app/build',
  'apps/ui/android/build',
  'apps/ui/android/.gradle',
  'packages/*/android/build',
  'apps/cli/tmp',
  'apps/cli/tools/unpacked',
  'apps/cli/*:*',
  'subagents/dev-plugin-projection-runtime-closure',
  '.env.local',
  'env.local',
  '*.log',
  '*.trace',
  '.DS_Store',
];

function yamlString(value) {
  return JSON.stringify(String(value));
}

export function resolveMutagenSessionName(targetName) {
  const encoded = [...String(targetName)].map((character) => {
    if (/^[A-Za-z0-9]$/.test(character)) return character;
    if (character === '-') return '--';
    if (character === '.') return '-d-';
    if (character === '_') return '-u-';
    return `-x${character.codePointAt(0).toString(16)}-`;
  }).join('');
  return `happier-${encoded}`;
}

export function mutagenProjectOwnerHeader(ownerId) {
  return `# hstack-owner: ${yamlString(ownerId)}`;
}

export function isMutagenProjectOwnedBy(contents, ownerId) {
  return String(contents ?? '').split(/\r?\n/, 2)[0] === mutagenProjectOwnerHeader(ownerId);
}

function withoutMutagenProjectOwner(contents) {
  return String(contents ?? '').replace(/^# hstack-owner: [^\r\n]*(?:\r?\n|$)/, '');
}

export function isEquivalentMutagenProject(existingContents, desiredContents) {
  return withoutMutagenProjectOwner(existingContents) === withoutMutagenProjectOwner(desiredContents);
}

export function renderMutagenProject({ sourceDir, targets, ownerId = null }) {
  const lines = [
    ...(ownerId == null
      ? ['# Generated by hstack. User configuration lives in dev-targets.json.']
      : [
          mutagenProjectOwnerHeader(ownerId),
          '# Generated by hstack. User configuration lives in dev-targets.json.',
        ]),
    'sync:',
    '  defaults:',
    '    mode: "one-way-replica"',
    '    ignore:',
    '      vcs: true',
    '      paths:',
    ...DEFAULT_IGNORES.map((entry) => `        - ${yamlString(entry)}`),
  ];
  for (const target of targets) {
    lines.push(
      `  ${resolveMutagenSessionName(target.name)}:`,
      `    alpha: ${yamlString(sourceDir)}`,
      `    beta: ${yamlString(`${target.ssh}:${target.repoDir}`)}`,
    );
  }
  return `${lines.join('\n')}\n`;
}

export function buildMutagenProjectArgs(action, projectFile) {
  const normalized = String(action ?? '').trim();
  const supported = new Set(['start', 'list', 'flush', 'pause', 'resume', 'reset', 'terminate']);
  if (!supported.has(normalized)) {
    throw new Error(`[dev-targets] unsupported Mutagen project action: ${normalized}`);
  }
  return [
    'project',
    normalized,
    ...(normalized === 'start' ? ['--paused', '--no-global-configuration'] : []),
    '--project-file',
    String(projectFile),
  ];
}
