import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse } from 'yaml';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '..', '..');

async function loadWorkflow(name) {
  return readFile(join(repoRoot, '.github', 'workflows', name), 'utf8');
}

test('promote-ui keeps workflow_dispatch inputs under GitHub limit with compact manual controls', async () => {
  const raw = await loadWorkflow('promote-ui.yml');
  const parsed = parse(raw);
  const inputs = parsed?.on?.workflow_dispatch?.inputs ?? {};
  const callInputs = parsed?.on?.workflow_call?.inputs ?? {};

  assert.ok(Object.keys(inputs).length <= 10, 'workflow_dispatch inputs must stay <= 10');

  for (const key of [
    'environment',
    'force_deploy',
    'run_tests',
    'source_ref',
    'allow_cross_promote',
    'bump',
    'deploy_web',
    'expo_action',
    'release_notes_id',
    'desktop_mode',
  ]) {
    assert.ok(inputs[key], `expected compact manual input ${key}`);
  }

  for (const legacyKey of ['expo_builder', 'expo_profile', 'expo_platform', 'desktop_build', 'desktop_publish_release']) {
    assert.equal(inputs[legacyKey], undefined, `manual input ${legacyKey} should be removed from workflow_dispatch`);
    assert.equal(callInputs[legacyKey], undefined, `workflow_call input ${legacyKey} should be removed from promote-ui`);
  }

  assert.ok(callInputs.desktop_mode, 'workflow_call should also define desktop_mode so reusable invocations validate');
});

test('release passes only declared inputs to reusable promote-ui', async () => {
  const release = parse(await loadWorkflow('release.yml'));
  const promoteUi = parse(await loadWorkflow('promote-ui.yml'));
  const declaredInputs = promoteUi?.on?.workflow_call?.inputs ?? {};
  const passedInputs = release?.jobs?.deploy_ui?.with ?? {};

  for (const inputName of Object.keys(passedInputs)) {
    assert.ok(
      declaredInputs[inputName],
      `release deploy_ui passes undeclared promote-ui input ${inputName}`,
    );
  }
});

test('promote-ui delegates web deploy branch promotion to pipeline script', async () => {
  const raw = await loadWorkflow('promote-ui.yml');
  assert.match(raw, /Promote exact release SHA to deploy branch/);
  assert.match(raw, /node scripts\/pipeline\/github\/promote-deploy-branch\.mjs/);
  assert.match(raw, /--github-output "\$GITHUB_OUTPUT"/);
  assert.match(raw, /steps\.promote_ref\.outputs\.new_sha/);
  assert.doesNotMatch(raw, /Resolve deploy branch SHA (?:before|after) promotion/);
  assert.match(raw, /group: deploy-ref-\$\{\{ github\.repository \}\}-\$\{\{ inputs\.environment \}\}-ui/);
  assert.match(raw, /cancel-in-progress: false/);
  assert.match(raw, /node scripts\/pipeline\/deploy\/trigger-webhooks\.mjs/);
  assert.doesNotMatch(raw, /steps\.deploy_meta\.outputs\./, 'promote-ui should not reference outputs from a nonexistent deploy_meta step');
  assert.doesNotMatch(raw, /Wait for deploy workflow/i);
});

test('promote-ui always verifies exact Mermaid generated bytes before candidate promotion', async () => {
  const raw = await loadWorkflow('promote-ui.yml');
  const parsed = parse(raw);
  const steps = parsed?.jobs?.validate_candidate?.steps ?? [];
  const verifyIndex = steps.findIndex((step) =>
    String(step?.run ?? '').includes('yarn --cwd apps/ui verify:mermaid-webview-bundle')
  );

  assert.ok(verifyIndex >= 0, 'candidate promotion must run the exact Mermaid bundle verifier');
  assert.equal(steps[verifyIndex]?.if, undefined, 'Mermaid freshness must not depend on optional run_tests');
  assert.ok(parsed?.jobs?.apply_bump, 'candidate mutation must complete before secret-free validation');
});

test('promote-ui carries the resolver authorized SHA into every exact-candidate checkout', async () => {
  const parsed = parse(await loadWorkflow('promote-ui.yml'));
  const resolvedSha = parsed?.jobs?.resolve_source?.outputs?.candidate_sha;
  const candidateCheckout = parsed?.jobs?.apply_bump?.steps?.find((step) =>
    step?.name === 'Checkout exact candidate as inert data'
  );

  assert.equal(resolvedSha, '${{ steps.candidate.outputs.authorized_sha }}');
  assert.equal(candidateCheckout?.with?.ref, '${{ needs.resolve_source.outputs.candidate_sha }}');
});

test('mobile reusable concurrency separates channel and deliverable lanes without canceling in-flight work', async () => {
  const parsed = parse(await loadWorkflow('build-ui-mobile-local.yml'));
  const group = String(parsed?.concurrency?.group ?? '');
  assert.equal(parsed?.concurrency?.['cancel-in-progress'], false);
  assert.match(group, /inputs\.source_ref/);
  assert.match(group, /inputs\.environment/);
  assert.match(group, /inputs\.platform/);
  assert.match(group, /inputs\.profile/);
  assert.match(group, /inputs\.action/);
  assert.match(group, /inputs\.publish_apk_release/);
  assert.doesNotMatch(group, /^build-ui-mobile-local-\$\{\{ github\.ref \}\}$/);
});
